services:
  db:
    image: postgres:16
    expose:
      - 5432 
    ports:
      - "5432:5432"
    environment:
       - POSTGRES_USER=dbuser
       - POSTGRES_PASSWORD=pass123
       - POSTGRES_DB=devops_db

    healthcheck:

      test: 
       - CMD-SHELL
       - pg_isready -U dbuser
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    volumes:
      - 'dslabdb:/var/lib/postgresql/data/'

  spring:
      image: db
      build:
        context: .
        dockerfile: nonroot-multistage.Dockerfile
      ports:
       - "8080:8080"
      depends_on:
        db:
          condition: service_healthy 
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/devops_db
        - SPRING_DATASOURCE_USERNAME=dbuser
        - SPRING_DATASOURCE_PASSWORD=pass123
      healthcheck:
         test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
         interval: 30s
         timeout: 30s
         retries: 3

  mailhog:
    build:
      context: .
      dockerfile: mail.Dockerfile
    ports:
      - "1025:1025" # SMTP port (εδώ στέλνει η Java)
      - "8025:8025" # Web UI (εδώ μπαίνεις εσύ να δεις το email)
volumes:
  dslabdb: